# Generated by Django 5.2.3 on 2025-07-12 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_cpf_customuser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='JustificationApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('justification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='accounts.justification')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_justifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
