# Generated by Django 5.2.3 on 2025-09-14 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='justification',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='justifications/'),
        ),
    ]
