# Generated by Django 5.2.3 on 2025-09-19 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_justification_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='distance_from_workplace_meters',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_valid_location',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='attendance',
            table='accounts_attendance',
        ),
    ]
