# Generated by Django 5.2.3 on 2025-09-21 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_attendance_distance_from_workplace_meters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='altitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='place_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
